theme: null
title: "Jefferson Li"
owner: "Jefferson Li"
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:name/

# optional site-wide defaults
defaults:
  - scope: { path: "" }
    values: { layout: default }
